POST http://localhost:7071/api/HttpStart

ESW

###

GET http://localhost:7071/runtime/webhooks/durabletask/instances/0fcfd5b974504dc3a000564f13359d96?taskHub=TestHubName&connection=Storage&code=qqafEDM34JiWLFke7XNvWjdm8LGU3sOTwJOeBjHtqJGs7wmHEF6MsQ==